### ISSUE TITLE
dos errores

### ISSUE THREAD

**Issue by nivek0o0** [nivek0o0/t07-repo#21]
hola tengo dos errores
```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    [1,2,3][5]
IndexError: list index out of range
```
y
```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    [1,2,3][5]
KeyError: python dictionarie
```

**Comment by nivek0o0** [comment]
ohh muchas gracias!
