### ISSUE TITLE
issue para el bonus

### ISSUE THREAD

**Issue by nivek0o0** [nivek0o0/t07-repo#8]
`Markdown de una linea`

```
markdown
de
multiples
lineas
```

**Comment by nivek0o0** [comment]
Traceback (most recent call last):
  File "C:/Users/acer/Desktop/nivek0o0-iic2233-2017-1/Tareas/T07/example.py", line 2, in <module>
    print(lista[3])
IndexError: list index out of range

**Comment by nivek0o0** [comment]
`Traceback (most recent call last):
  File "C:/Users/acer/Desktop/nivek0o0-iic2233-2017-1/Tareas/T07/example.py", line 2, in <module>
    print(lista[3])
IndexError: list index out of range`

**Comment by nivek0o0** [comment]
```
Traceback (most recent call last):
  File "C:/Users/acer/Desktop/nivek0o0-iic2233-2017-1/Tareas/T07/example.py", line 2, in <module>
    print(lista[3])
IndexError: list index out of range
```

**Comment by nivek0o0** [comment]
```
`Traceback (most recent call last):
  File "C:/Users/acer/Desktop/nivek0o0-iic2233-2017-1/Tareas/T07/example.py", line 2, in <module>
    print(lista[3])
IndexError: list index out of range`
```
